### ISSUE TITLE
no more fip info with lms 7.9.2

### ISSUE THREAD

**Issue by tutle** [PaulWebster/RadioFrance#2]
I just upgrade to lms 7.9.2 on my synology because I had youtube plugin problem.
LogitechMediaServer-x86_64-7.9.2-168.0030.spk
https://pinkdot.myds.me/sspks/?fulllist=true
It works fine but now, I just have france inter and france culture infos with the **"radio france" plugin (v0.1.27)**, nothing else. Very disapointed.
I can't live without this plugin, any solution to fix it ?
Thanks a lot
Yvan

**Comment by PaulWebster** [comment]
Working fine here with 7.9.2 and 7.9.3 but not in same environment as you.

Please check the LMS logs for clues.
Can increase log level from LMS web interface via Settings/Advanced/Logging/RadioFrance = Debug

Might be SSL issue.

**Comment by tutle** [comment]
I try to understand but I'm not an expert. SSL ?
Where do I find the debug mode of the plugin (nas)?

**Comment by PaulWebster** [comment]
Check the LMS logs - you can see them from the LMS web interface
Settings/Information
Typically this is via
h t t p : / / yourserverip:9000
(Without spaces and with the IP address of your LMS system - your NAS in your case)
It might not be “9000” on your system as I think Synology used that for something else but you probably know the right thing to use in your setup.

To get the plugin debug info use the info that I put in the first reply.

**Comment by tutle** [comment]
It works again back after uninstalling the plugin Airplay bridge. Cooool.

**Comment by PaulWebster** [comment]
Strange.
There should not be any relationship between those plugins but good that it works again.

**Comment by tutle** [comment]
Hello, hope your are ok in this so strange period.
I lost again the radio France informations, 
lms v8.0.0
radio france plugin 0.1.28
the log
[20-04-21 07:31:29.0635] Slim::Networking::Async::connect (114) Failed to connect to api.radiofrance.fr:443, because
Net::HTTP: connect: timeout
Sincerely.
Yvan

**Comment by PaulWebster** [comment]
That implies an underlying network problem.
The plugin (usually) works fine with LMS 8.
Has it worked at all for you since moving to LMS 8 Beta?
Has anything else changed - especially related to networking?

**Comment by tutle** [comment]
Thanks for your answer, It stopped to work even on previous release of lms 7.9
I'm a little bit lost, LMS is installed on my NAS Synology, what kind of network problem ?
Sincerely

**Comment by tutle** [comment]
Solved by rebooting the nas, strange...
