### ISSUE TITLE
No more song information displayed

### ISSUE THREAD

**Issue by Ph-St** [PaulWebster/RadioFrance#5]
Hi Paul,

first of all thanks for this great plugin! I've been using it for some time now to play FIP and get song info and it worked very well. However, today I noticed that while the stream works fine (I'm using the AAC option) no more information are displayed either on the device (I have a classic Logitech Squeezebox) nor in the LMS (8.5.2). I've added another FIP station (Jazz) and tried the other stream options, but not dice. Any ideas what I could try? My plugin version is displayed as v0.4.14.

Thanks!
Philipp

**Comment by PaulWebster** [comment]
Looks like they have just changed their API again.
I should be able to resolve it.

**Comment by PaulWebster** [comment]
I have just pushed out build 0.4.15 that I think resolves this.
The changes are not in GitHub (yet) but should appear via LMS plugin updates in next few hours.

**Comment by Ph-St** [comment]
Brilliant, many thanks. Let's hope they won't fiddle with the API anymore...

**Comment by Ph-St** [comment]
Just updated and song info is back! Thanks!

**Comment by Ph-St** [comment]
Just updated and song info is back! Thanks!
